### PR TITLE
Fixes #273 #274

### LINKED ISSUE #273: PDF preview shows explorer view instead
**Version used**
3.12

**Describe the bug**
When hovering over a pdf, the preview doesn't render the document view, but instead shows the explorer view of the folder where the document resides.

**To Reproduce**
This issue is not restricted to a single PDF. Tried this on over 20 different files.
Not restricted to a single tenant. Tried on a Developer and a Live tenant.
Search for a file and hover (click) on it to experience the behavior.

**Expected behavior**
The PDF preview must be shown and not the explorer view of its parent folder.

**Screenshots**
Screenshot attached.

**Desktop (please complete the following information):**
On Win 10, witnessed on Chrome (81.0.4044.138), Firefox (68.8.0 ESR), New Edge (81.0.416.72)

**Additional context**
The PDF preview of the out of the box search works just fine. Issue only with the PNP modern search.

Search_PDF_Issue_DevTenant

### PR DESCRIPTION
**Pull request by wobba**
Fixes #273 #274 
Replaces #275

### CODE REVIEW

File: search-parts/src/services/TemplateService/BaseTemplateService.tsx [hunk 1]
```diff
@@ -763,7 +763,7 @@ abstract class BaseTemplateService {
                         let renderElement = React.createElement(
                             PreviewContainer,
                             {
-                                elementUrl: url.replace('interactivepreview', 'embedview'),
```
Comment (wobba) [inline search-parts/src/services/TemplateService/BaseTemplateService.tsx:766]: This fixes #273
